### ISSUE TITLE
Wait for a specfied commit's deployment

### ISSUE THREAD

**Issue by Menci** [WalshyDev/cf-pages-await#1]
Sometimes when I pushed a commit in GitHub Actions to a branch to trigger CF Pages's build, a new deployment won't always be created immediately. I think we should accept a commit ref and check if the ref exists in the deployments array.

**Comment by Menci** [comment]
The commit hash is in API response's `.result[*].deployment_trigger.metadata.commit_hash`.

**Comment by WalshyDev** [comment]
Added in v1.1.0, ty!

**Comment by Menci** [comment]
Consider sometimes the commit triggering the workflow may not the same as the commit triggering the Pages deployment. For example [pushing some code to another branch](https://github.com/Menci/oi-wiki-mirror/blob/03f681a1ae264a8665213b93404e7969fd9e1982/.github/workflows/build.yaml#L82) to trigger Pages deployment.

I'd prefer to add a `commitHash` input for the action. I did it in https://github.com/Menci/cf-pages-await/commit/54e666c81e4948cfccd5562614839952c0f827f5. I can open a PR if you like it.

**Comment by WalshyDev** [comment]
Ah, this makes sense, feel free to open a PR otherwise I will get to it soon :+1:
