### ISSUE TITLE
Main differences from pages-action

### ISSUE THREAD

**Issue by IanVS** [WalshyDev/cf-pages-await#12]
Hi, I'm a bit confused when someone might prefer using this versus https://github.com/cloudflare/pages-action.  Maybe you could explain a bit in the readme what the differences are?

**Comment by andreiborisov** [comment]
`cloudflare/pages-action` builds on GitHub Actions runners and uploads results to Cloudflare Pages through API.

This action waits for Cloudflare Page builds, which run on Cloudflare infrastructure (this setup is active if you use Cloudflare's GitHub App and their git integration).

**Comment by IanVS** [comment]
Thanks for explaining!
