### ISSUE TITLE
"Waiting for the deployment to start" when used in Workflows that create new commits

### ISSUE THREAD

**Issue by connerdavis47** [WalshyDev/cf-pages-await#3]
I'm using this action in a workflow that uses [semantic-release](https://github.com/semantic-release/semantic-release) to automatically generate release commits.

[`cf-pages-await` uses the variable `GITHUB_SHA` to refer to the original commit invoking the workflow](https://github.com/WalshyDev/cf-pages-await/blob/main/src/action.ts#L30), but my latest commit is always newer because of `semantic-release`. So it "[waits] for the deployment to start" forever.

It would be nice to have the ability to toggle whether this action checks for a commit match or just wait for the latest build blindly.

My solution to this for now is to rearrange my action so that I wait for the Cloudflare Pages build first, do my post-build tasks, *then* run the release. No big deal at all.

This problem would also get naturally solved by support to filter out commits from auto deployment on Cloudflare Pages with, e.g., `skip ci` in the message.

**Comment by connerdavis47** [comment]
This isn't really an issue inherent with the Action itself but I figured I would raise the issue in case someone else finds themselves in the same situation.

**Comment by Menci** [comment]
I'll open a PR for it (#1).

**Comment by motiejunas** [comment]
Same issue. I have an action which mirrors repo to another GitHub repo that actually triggers CF Pages build, so the commit hash does not match of course.

Btw, this mirroring is a workaround I do to deploy multiple CF Pages from monolith repo. There is a limitation that you cannot build multiple CF Pages out of a single repo.

**Comment by Menci** [comment]
I've opened a pull request (#5) for this. You can specify a commit hash after that got merged.

ping @WalshyDev

**Comment by WalshyDev** [comment]
Hey sorry, been a bit crazy with this new job. Will try and get to this at the weekend! Appreciate the PR @Menci

**Comment by motiejunas** [comment]
@WalshyDev how was your weekend?
