### ISSUE TITLE
It doesn't work as dependent on each deployment.

### ISSUE THREAD

**Issue by Kim-Chuljoong** [WalshyDev/cf-pages-await#9]
Even when one deployment is finished, it seems to keep waiting when another queued deployment starts.
Even if the deployments in the queue are in succession, can't each work individually?

**Comment by WalshyDev** [comment]
I'd recommend using the `commitHash` input option which should resolve that.

Something like: `commitHash: ${{ github.sha }}` will make sure it gets the deployment for this specific push

**Comment by Kim-Chuljoong** [comment]
In my case, `commitHash: ${{ steps.push-changes.outputs.commit-hash }}` in the README.md didn't work, but `commitHash: ${{ github.sha }}` in the reply worked the way I wanted it to.
thanks!

**Comment by mbhave** [comment]
I want to trigger this action based on something external to github changing, for example, if content in my CMS changes. I can do that using the `repository_dispatch` trigger. In this case, will it keep waiting even when a deployment is done but there are other queued?
